import { Header } from "@/components/header";
import DarkBox from "@/components/simple-styles/dark-box";
import CustomToaster from "@/components/toast/custom-toaster";
import type { Metadata } from "next";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import AriaRouterProvider from "./router-context";
import { Raleway } from 'next/font/google';
import { Playfair_Display } from 'next/font/google';

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const raleway = Raleway({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-raleway',
});

const playfairDisplay = Playfair_Display({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-playfair-display',
})

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" data-theme="clocktower" className={`${raleway.variable} ${playfairDisplay.variable}`}>
            <body>
                <AriaRouterProvider>
                    <CustomToaster />
                    <div className="flex h-screen flex-col justify-between">
                        <Header />
                        <main className="flex grow overflow-auto bg-gray-700">
                            {children}
                        </main>
                        <DarkBox>
                            <footer
                                className={`border-t-2 border-solid border-gray-600 p-2 text-sm `}
                            >
                                This project is not affiliated with The
                                Pandemonium Institute. All roles & content are
                                the property of Steven Medway and The
                                Pandemonium Institute.
                            </footer>
                        </DarkBox>
                    </div>
                </AriaRouterProvider>
            </body>
        </html>
    );
}
