import { Header } from "@/components/header";
import DarkBox from "@/components/simple-styles/dark-box";
import "@fontsource/old-standard-tt/700.css";
import "@fontsource/raleway/400.css";
import "@fontsource/raleway/600.css";
import "@fontsource/raleway/700.css";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" data-theme="clocktower">
            <body>
                <div className="flex h-screen flex-col justify-between">
                    <Header />
                    <main className="flex grow overflow-auto bg-gray-700">
                        {children}
                    </main>
                    <DarkBox>
                        <footer
                            className={`p-2 text-sm border-t-2 border-gray-600 border-solid `}
                        >
                            This project is not affiliated with The Pandemonium
                            Institute. All roles & content are the property of
                            Steven Medway and The Pandemonium Institute.
                        </footer>
                    </DarkBox>
                </div>
            </body>
        </html>
    );
}
